format_version: 3
pipelines:
  HelloApp:
    group: myFirstpipeline
    label_template: "${COUNT}"
    lock_behavior: none
    materials:
      git:
        url: https://github.com/htetgit/App-update.git
        branch: main
        shallow_clone: false
        auto_update: true
    stages:
      - name: Build
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        jobs:
          - name: Compile
            tasks:
              - exec:
                  command: go
                  arguments: ["mod", "tidy"]
                  working_directory: "."
              - exec:
                  command: go
                  arguments: ["build", "-o", "main", "."]
                  working_directory: "."
      - name: Dockerize
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        jobs:
          - name: BuildDockerImage
            tasks:
              - exec:
                  command: docker
                  arguments: ["build", "-t", "my-golang-app", "."]
                  working_directory: "."
              - exec:
                  command: docker
                  arguments: ["run", "-d", "-p", "8080:8080", "my-golang-app"]
                  working_directory: "."
